name = "lean-eval"
defaultTargets = ["LeanEval"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "c5ea00351c28e24afc9f0f84379aa41082b1188f"

[[require]]
name = "Cli"
git = "https://github.com/leanprover/lean4-cli"
rev = "v4.30.0"

[[lean_lib]]
name = "LeanEval"

[[lean_lib]]
name = "EvalTools"

[[lean_exe]]
name = "extract_theorem"
root = "EvalTools.ExtractTheorem"

[[lean_exe]]
name = "eval_inventory"
root = "EvalTools.ProblemInventory"

[[lean_exe]]
name = "lean-eval"
root = "EvalTools.Main"

[[lean_exe]]
name = "test_validate_submission"
srcDir = "tests/lean"
root = "EvalToolsTests.ValidateSubmissionTest"

[[lean_exe]]
name = "test_check_comparator_installation"
srcDir = "tests/lean"
root = "EvalToolsTests.CheckComparatorInstallationTest"

[[lean_exe]]
name = "test_generate"
srcDir = "tests/lean"
root = "EvalToolsTests.GenerateTest"
