id = "fermat_last_theorem"
title = "Fermat's Last Theorem"
test = false
module = "LeanEval.NumberTheory.FermatLastTheorem"
holes = ["fermat_last_theorem"]
submitter = "Xuanji Li"
notes = "Fermat's Last Theorem: a^n + b^n = c^n has no nontrivial natural solution when n >= 3."
source = "https://en.wikipedia.org/wiki/Fermat%27s_Last_Theorem"
informal_solution = "via https://en.wikipedia.org/wiki/Modularity_theorem"
