id = "neukirch_uchida"
title = "Neukirch–Uchida theorem"
test = false
module = "LeanEval.NumberTheory.NeukirchUchida"
holes = ["neukirch_uchida"]
submitter = "Junyan Xu"
source = "Jürgen Neukirch, Alexander Schmidt, Kay Wingberg. *Cohomology of Number Fields*, Theorem 12.2.1."
