id = "permute_to_unimodal"
title = "A competition programming problem about permuting a permutation to be unimodal"
test = false
module = "LeanEval.ProgramVerification.PermuteToUnimodal"
holes = ["minRearrange_correct"]
submitter = "Julia M. Himmel"
source = "NWERC 2025 Problem G, see https://2025.nwerc.eu/problem-set.pdf"
informal_solution = "See https://2025.nwerc.eu/solutions.pdf for a sketch of the correctness, which goes in two steps: construct a quadratic-time dynamic programming solution, then efficiently evaluate that in O(n log n). The hard part is showing the correspondence between LISs of prefixes of the constructed sequence and values of the DP."
